Created Landing Pages using HTML and CSS
kumari-arya/Landing-Page pull request #1
Opened 2023-05-03 09:13 UTC by kumari-arya

2023-05-03 09:48 UTC, roopaljasnani requested changes
Another point that I've continually highlighted for your PRs is - 

It is important that you file out other meta details in your PR like a proper title, description (with proper screenshots/screen recordings when some UI work is involved), assignee, reviewers, etc.

Read about how to properly fill in such details in this [guide from our handbook](https://github.com/jalantechnologies/handbook/blob/main/engineering/pr-etiquette.md).

Pls also follow [this PR template](https://github.com/jalantechnologies/boilerplate-next-typescript/blob/develop/.github/pull_request_template.md) when filling out the description in this & upcoming PRs.

Pls follow this by default and should not need reminding again, @kumari-arya

2023-05-03 09:48 UTC, roopaljasnani commented on index.html
> +            <h1 class="second-header">Some random information</h1>
An HTML page cannot have multiple h1 tags

2023-05-03 09:48 UTC, roopaljasnani commented on index.html
> +            <div class="first">
consider using section tags for emphasizing blocks

2023-05-03 09:48 UTC, roopaljasnani commented on index.html
> +        <div class="second">
consider using section tags for emphasizing blocks

2023-05-03 09:48 UTC, roopaljasnani commented on index.html
> +        <div class="third">
consider using section tags for emphasizing blocks,

for this particular section - a figure & a blockquote tag can also be considered

2023-05-03 09:48 UTC, roopaljasnani commented on index.html
> +            <button class="fourth-button"> Sign-up</button>
remove space before button

2023-05-03 09:48 UTC, roopaljasnani commented on index.html
> +        <div class="footer">
use footer  tag here

2023-05-03 09:48 UTC, roopaljasnani commented on style.css
> +
remove space from here

2023-05-03 09:48 UTC, roopaljasnani commented on style.css
> +
remove space

2023-05-03 09:48 UTC, roopaljasnani commented on style.css
> +}
add space after each block

2023-05-03 09:48 UTC, roopaljasnani commented on style.css
> +{
formatting in the line is entirely off

2023-05-03 09:48 UTC, roopaljasnani commented on style.css
> +    margin-right: auto;
use margin shorthand

2023-05-03 09:48 UTC, roopaljasnani commented on style.css
I think I've repeated this point now for all your PRs - Pls make a habit of working hand-in-hand with helpful tools like [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) & [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) that come along with the VSCode editor & configure them to run & format files automatically on save.

I should not see the need to give this reminder again please, @kumari-arya.

2023-05-04 02:47 UTC, kumari-arya commented
> Another point that I've continually highlighted for your PRs is -
> 
> It is important that you file out other meta details in your PR like a proper title, description (with proper screenshots/screen recordings when some UI work is involved), assignee, reviewers, etc.
> 
> Read about how to properly fill in such details in this [guide from our handbook](https://github.com/jalantechnologies/handbook/blob/main/engineering/pr-etiquette.md).
> 
> Pls also follow [this PR template](https://github.com/jalantechnologies/boilerplate-next-typescript/blob/develop/.github/pull_request_template.md) when filling out the description in this & upcoming PRs.
> 
> Pls follow this by default and should not need reminding again, @kumari-arya

Updated. Please see once again

2023-05-04 02:48 UTC, kumari-arya commented
Resolve all raised issues.

2023-05-04 06:35 UTC, roopaljasnani approved these changes

2023-05-04 08:49 UTC, merged